name: Smart Contract Build & Test

on:
  push:
    branches:
      - main
      - "v*.[0-9]"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - name: Contract Build
        run: |
          cargo build --target wasm32-unknown-unknown --release
      - name: Code Verifications
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Format code
        run: |
          cargo fmt --check
      - name: Code Tests and coverage
        uses: actions-rs/tarpaulin@044a1e5bdace8dd2f727b1af63c1d9a1d3572068 # v0.1.3
        with:
          version: 0.22.0
          args: --all-features --fail-under 98.0 --out Lcov
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"
